spring:
  application:
    name: "Spring_AI"
  ai:
    dashscope:
      api-key: ${DASHSCOPE_API_KEY}
      chat:
        options:
          model: qwen-max
          temperature: 0.8
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: deepseek-r1:8b
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/SpringBoot_Test?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: "LYClyc...550"
  mybatis-plus:
    mapper-locations: classpath*:/mapper/**/*.xml
    type-aliases-package: com.sias.spring_ai_test.entity.PO
    configuration:
      map-underscore-to-camel-case: true
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    org.springframework.ai.chat.client: debug
    com.sias.spring_ai_test: debug

server:
  port: 8080